jwt:
  secret: asd121rR2fmkdRWNfknIDNfnd23r3FSNfemKOM42ddko5K43kfn4

  access:
    expiration: 10000000
    header: Authorization

  refresh:
    expiration: 30000000
    header: Authorization-refresh